
package universidad.vista;

public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu5 = new javax.swing.JMenu();
        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mSalir = new javax.swing.JMenuItem();
        menuMateria = new javax.swing.JMenu();
        mMateria = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mAlumno = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mInscripcion = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        mNotas = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        mListadoAlMat = new javax.swing.JMenuItem();

        jMenu5.setText("jMenu5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 624, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 409, Short.MAX_VALUE)
        );

        jMenu1.setText("Archivo");

        mSalir.setText("Salir");
        mSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSalirActionPerformed(evt);
            }
        });
        jMenu1.add(mSalir);

        jMenuBar1.add(jMenu1);

        menuMateria.setText("Materias");

        mMateria.setText("Formulario Materia");
        mMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mMateriaActionPerformed(evt);
            }
        });
        menuMateria.add(mMateria);

        jMenuBar1.add(menuMateria);

        jMenu3.setText("Alumnos");

        mAlumno.setText("Formulario Alumno");
        mAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAlumnoActionPerformed(evt);
            }
        });
        jMenu3.add(mAlumno);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Inscripciones");

        mInscripcion.setText("Formulario de Inscripcion");
        mInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mInscripcionActionPerformed(evt);
            }
        });
        jMenu4.add(mInscripcion);

        jMenuBar1.add(jMenu4);

        jMenu7.setText("Notas");

        mNotas.setText("Manipular Notas");
        mNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mNotasActionPerformed(evt);
            }
        });
        jMenu7.add(mNotas);

        jMenuBar1.add(jMenu7);

        jMenu6.setText("Consultas");

        mListadoAlMat.setText("Listado de alumnos por materia");
        jMenu6.add(mListadoAlMat);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mSalirActionPerformed

    private void mMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mMateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mMateriaActionPerformed

    private void mAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mAlumnoActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        VistaAlumno vm=new VistaAlumno();
        vm.setVisible(true);
        escritorio.add(vm);
        escritorio.moveToFront(vm);
    }//GEN-LAST:event_mAlumnoActionPerformed

    private void mInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mInscripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mInscripcionActionPerformed

    private void mNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mNotasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mNotasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mAlumno;
    private javax.swing.JMenuItem mInscripcion;
    private javax.swing.JMenuItem mListadoAlMat;
    private javax.swing.JMenuItem mMateria;
    private javax.swing.JMenuItem mNotas;
    private javax.swing.JMenuItem mSalir;
    private javax.swing.JMenu menuMateria;
    // End of variables declaration//GEN-END:variables
}
