/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidad.vista;

import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import universidad.entidades.Alumno;
import universidad.entidades.Inscripcion;
import universidad.entidades.Materia;
import universidad.modelo.AlumnoData;
import universidad.modelo.Conexion;
import universidad.modelo.InscripcionData;
import universidad.modelo.MateriaData;


/**
 *
 * @author lbiolatti
 */
public class VistaIncripcion extends javax.swing.JInternalFrame {
Conexion c=new Conexion();
InscripcionData id = new InscripcionData(c);
AlumnoData ad = new AlumnoData(c);
MateriaData md = new MateriaData(c);
DefaultTableModel modelo;
    /**
     * Creates new form VistaIncripcion
     */
    public VistaIncripcion() {
        initComponents();
        cargaAlumnos();
        modelo = new DefaultTableModel();
        armarCabecera();
    }
    public void cargaAlumnos(){
        List <Alumno> lista = ad.obtenerAlumnos();
        for(Alumno a:lista){
            cbAlumno.addItem(a);
        }
    }
    public void armarCabecera(){
        ArrayList<Object> columnas = new ArrayList<>();
        columnas.add("ID");
        columnas.add("Nombre");
        
        for(Object i:columnas){
        modelo.addColumn(i);
        }
        tabla.setModel(modelo);
    }
    public void borrarFilas(){
    
        int a = modelo.getRowCount()-1;
        for(int i=a;i>=0;i--){
            modelo.removeRow(i);
            
        }
    }
    public void cargarInscriptas(){
        borrarFilas();
        
        Alumno seleccionado = (Alumno) cbAlumno.getSelectedItem();
        List<Materia> lista=id.obtenerMateriasCursadas(seleccionado.getIdAlumno());
            for(Materia m:lista){
                modelo.addRow(new Object[]{m.getIdMateria(),m.getNombreMateria()});
            }
    }
    public void cargarNoInscriptas(){
        borrarFilas();
        Alumno seleccionado = (Alumno) cbAlumno.getSelectedItem();
        List<Materia> lista=id.obtenerMateriasNoCursadas(seleccionado.getIdAlumno());
        for(Materia m:lista){
                modelo.addRow(new Object[]{m.getIdMateria(),m.getNombreMateria()});
            }
        
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbAlumno = new javax.swing.JComboBox<>();
        rNoInscripto = new javax.swing.JRadioButton();
        rInscripto = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        bInscribir = new javax.swing.JButton();
        bEliminrInsc = new javax.swing.JButton();
        bSalir = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FORMULARIO DE INSCRIPCION");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("ALUMNO:");

        buttonGroup1.add(rNoInscripto);
        rNoInscripto.setText("No Inscripto");
        rNoInscripto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rNoInscriptoActionPerformed(evt);
            }
        });

        buttonGroup1.add(rInscripto);
        rInscripto.setText("Inscripto");
        rInscripto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rInscriptoActionPerformed(evt);
            }
        });

        jLabel3.setText("LISTADO DE MATERIAS");

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        bInscribir.setText("Inscribir");
        bInscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInscribirActionPerformed(evt);
            }
        });

        bEliminrInsc.setText("Eliminar inscripcion");
        bEliminrInsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminrInscActionPerformed(evt);
            }
        });

        bSalir.setText("Salir");
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(rInscripto, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(rNoInscripto)
                        .addGap(175, 175, 175))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(191, 191, 191))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))))
            .addGroup(layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bInscribir)
                .addGap(40, 40, 40)
                .addComponent(bEliminrInsc, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(bSalir)
                .addGap(90, 90, 90))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rNoInscripto)
                    .addComponent(rInscripto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bInscribir)
                    .addComponent(bEliminrInsc)
                    .addComponent(bSalir))
                .addGap(0, 123, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rNoInscriptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rNoInscriptoActionPerformed
        // TODO add your handling code here:
        rInscripto.setSelected(false);
        cargarNoInscriptas();
        bEliminrInsc.setEnabled(false);
        bInscribir.setEnabled(true);
    }//GEN-LAST:event_rNoInscriptoActionPerformed

    private void rInscriptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rInscriptoActionPerformed
        // TODO add your handling code here:
        rNoInscripto.setSelected(false);
        cargarInscriptas();
        bInscribir.setEnabled(false);
        bEliminrInsc.setEnabled(true);
    }//GEN-LAST:event_rInscriptoActionPerformed

    private void bInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInscribirActionPerformed
        // TODO add your handling code here:
        int fSel=tabla.getSelectedRow();
        if(fSel !=-1){
        Alumno a=(Alumno) cbAlumno.getSelectedItem();
        int idMateria=(int) modelo.getValueAt(fSel,0);
        String nomMat=(String) modelo.getValueAt(fSel,1);
        
        Materia m=new Materia(idMateria,nomMat);
        
        Inscripcion i=new Inscripcion(a,m,0);
        id.guardarInscripcion(i);
        borrarFilas();
        }
    }//GEN-LAST:event_bInscribirActionPerformed

    private void bEliminrInscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminrInscActionPerformed
        // TODO add your handling code here:
        int fSel=tabla.getSelectedRow();
        if(fSel !=-1){
        Alumno a=(Alumno) cbAlumno.getSelectedItem();
        int idMateria=(int) modelo.getValueAt(fSel,0);
        id.eliminarInscripcion(a.getIdAlumno(), idMateria);
        
        borrarFilas();
        }
    }//GEN-LAST:event_bEliminrInscActionPerformed

    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_bSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bEliminrInsc;
    private javax.swing.JButton bInscribir;
    private javax.swing.JButton bSalir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<Alumno> cbAlumno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rInscripto;
    private javax.swing.JRadioButton rNoInscripto;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
